version: 2

models:
  - name: fact_orders
    description: "Fact table for orders and their item-level metrics"
    columns:
      - name: order_id
        description: "Primary key for each order"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Should always map to a valid customer"
        tests:
          - not_null
      - name: total_item_value
        description: "price + freight_value per order item"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "total_item_value >= 0"

  - name: dim_customer
    description: "Dimension table with customer location info"
    columns:
      - name: customer_id
        description: "Unique customer ID"
        tests:
          - not_null
          - unique
      - name: customer_state
        description: "Should not be null"
        tests:
          - not_null

  - name: dim_product
    description: "Dimension table for product attributes"
    columns:
      - name: product_id
        description: "Unique product ID"
        tests:
          - not_null
          - unique
      - name: product_category_name
        description: "Product should belong to a category"
        tests:
          - not_null

  - name: dim_seller
    description: "Dimension table with seller information"
    columns:
      - name: seller_id
        description: "Unique seller ID"
        tests:
          - not_null
          - unique
      - name: seller_state
        description: "Seller state should be defined"
        tests:
          - not_null

  - name: dim_date
    description: "Dimension table for calendar dates derived from orders"
    columns:
      - name: date_id
        description: "Date key"
        tests:
          - not_null
      - name: year
        description: "Year portion of the order date"
        tests:
          - not_null
      - name: month
        description: "Month portion of the order date"
        tests:
          - not_null
