version: 2

sources:
  - name: brazil_e_commerce
    database: concise-faculty-452613-a1
    tables:
      - name: customers
      - name: orders
      - name: geolocation
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: product_category_name_translations
      - name: products
      - name: sellers