version: 2

models:
  - name: dim_customers
    description: "Dimension table for customers."
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not null

models:
  - name: dim_sellers
    description: "Dimension table for seller."
    columns:
      - name: seller_id
        description: "The primary key for this table"
        tests:
          - unique
          - not null

models:
  - name: dim_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
